Algoritmo "Variáveis"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Vinícius Camargo
// Data atual  : 24/09/2020
Var
// Seção de Declarações das variáveis 

   endereco, cidade, primeiroNome, segundoNome: caractere
   idade: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo